version: '3.5'
services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: server.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - server.env # configure postgres
    depends_on:
      - database

