# Generated by Django 4.0 on 2022-01-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemfile',
            unique_together={('item', 'image')},
        ),
        migrations.AlterIndexTogether(
            name='itemfile',
            index_together={('item', 'image')},
        ),
    ]
