# Generated by Django 4.0 on 2022-01-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_space', '0004_alter_itemfile_md5'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemfile',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='itemfile',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemfile',
            unique_together={('item', 'md5')},
        ),
        migrations.AlterIndexTogether(
            name='itemfile',
            index_together={('item', 'md5')},
        ),
    ]
