# Generated by Django 4.0 on 2022-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_space', '0005_alter_itemfile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
